### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by TBbusiness** [GijsGoudzwaard/APPointment#7]
Hi,
Looks like a great repository. I am trying to build it up to test it out, but I was unable to login successfully. I do get to login screen and after I login via server.php it redirects to subdomain "apperture.domain.com"  that is empty. 
Any clue what am I doing wrong?
My link for test: [link](http://mariapps.tryfcomet.com/laravel/server.php)

Thanks in advance for any help!
Kind regards

**Comment by GijsGoudzwaard** [comment]
The base url needs to be accessible. It expects that http://mariapps.tryfcomet.com will be used for the app and not for something else, which is the case now. You'll need to create a new url for your app.

**Comment by TBbusiness** [comment]
Thank you for reply. I have tried to build it locally with main domain, but without luck.
This are the first lines from my .env file (local development server, different for live):
```
APP_ENV=local
APP_KEY=base64:iZmnxHR7QiRtxzxgiXdILKGbM+kclekgIlEMDbTHd6c=
APP_DEBUG=false
APP_LOG_LEVEL=debug
APP_URL=http://192.168.33.10/

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=33060
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret
```

It always tries to access subdomain for company (example: http://aperture.192.168.33.10), but browser doesn't load anything.
I have also tried changing to _APP_URL= http://localhost_  on live website and local development server without luck. Not sure what am I doing wrong.

**Comment by GijsGoudzwaard** [comment]
You can't add characters in front of an ip address. This app creates a different 'environment' per customer which is prepended to the url. For this to work you need a url with characters `[a-z]`. For local development [valet](https://laravel.com/docs/5.7/valet) is useful.
